---
apiVersion: v1
kind: Service
metadata:
  name: currency-exchange
  namespace: microservice
  labels:
    app: currencyexchange
spec:
  ports:
    - port: 8001
      protocol: TCP
      targetPort: 8001
  selector:
    app: currencyexchange
    tier: compute
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: currency-exchange
  namespace: microservice
  labels:
    app: currencyexchange
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: currencyexchange 
  template:
    metadata:
      labels:
        app: currencyexchange
        tier: compute
    spec:
      containers:
        - image: deepak16j/currency-exchange:latest
          imagePullPolicy: Always
          name: currency-exchange
          env:
            - name: MYSQL_DB_USER
              value: root
            - name: MYSQL_DB_PASSWORD
              value: root
            - name: MYSQL_DB_HOST
              value: db-service.microservice
            - name: MYSQL_DB_PORT
              value: "3306"
          ports:
            - containerPort: 8001
              name: currency