---
apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: microservice
  labels:
    app: db-service
spec:
  ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    app: db
    tier: database
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: microservice
  labels:
    app: db
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
        tier: database
    spec:
      containers:
        - image: mysql:latest
          name: db-container
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root

          ports:
            - containerPort: 3306
              name: db